package com.softtech.android_structure.features

object FeatureConstants {
    const val SERVICE_NAME_KEY="SERVICEName"

    const val KEY_UPDATE_PASSWORD="KEY_update_PASSWORD"
    const val KEY_PHONE_NUMBER="KEY_PHONE_NUMBER"
    const val SERVICE_KEY="SERVICE"
    const val SCREEN_BABYSITTER="babysitter"
    const val SCREEN_CHEF="chef"
    const val SCREEN_GARDENER="gadener"
    const val SCREEN_MAID="MAID"
    const val SCREEN_CHAUFER="SCREEN_CHAUFER_KEY"

    const val KEY_CONTRACT_TYPE = "KEY_ORDER_TYPE"

    const val KEY_CONTRACT_ID = "KEY_CONTRACT_ID"

    const val KEY_WORKER_PARAMS = "KEY_WORKER_PARAMS"

    const val KEY_WORKER_TYPE = "KEY_WORKER_TYPE"

    const val SCREEN_MY_CONTRACTS="myCOntract"

    const val VERIFICATION_CODE_KEY = "VERIFICATION_CODE_KEY"


    const val KEY_UNAUTHORIZATION_TOKEN = 401

    const val KEY_ACCOUNT_NOT_EXIST = 523

    const val KEY_ACCOUNT_NOT_VERIFY = 706

    const val KEY_ACCOUNT_LOGED_OTHER_DEVICE= 315


    const val KEY_EMAIL_ALREADY_VERIFY = 458

    const val KEY_ACCOUNT_BLOCKED = 410

    const val KEY_ACCOUNT_NOT_TOKEN_SET = 403

    val EXPIRE_SESSION_LIST_STATUS = arrayOf(KEY_UNAUTHORIZATION_TOKEN,KEY_ACCOUNT_NOT_EXIST,KEY_ACCOUNT_NOT_VERIFY,KEY_ACCOUNT_BLOCKED,KEY_ACCOUNT_NOT_TOKEN_SET)

    const val CATEGORY_MAID=1
    const val CATEGORY_CHAUFEUR=2
    const val CATEGORY_GARDENER=3
    const val CATEGORY_BABYSITTER=4
    const val CATEGORY_CHEF=5
    const val FACEBOOK_RESULT_REQUEST_CODE=64206
    const val GOOGLE_RESULT_REQUEST_CODE=1992

}