package com.softtech.android_structure.domain.validations

object ValidationConstants {

    const val FULL_NAME_MIN_LENGTH_VALIDATOR: String = "FULL_NAME_MIN_LENGTH_VALIDATOR"

    const val CORPORATE_NAME_MIN_LENGTH_VALIDATOR: String = "CORPORET_NAME_MIN_LENGTH_VALIDATOR"

    const val PASSWORD_MIN_LENGTH_VALIDATOR: String = "PASSWORD_MIN_LENGTH_VALIDATOR"

    const val MIN_LENGTH_VALIDATOR="MIN_LENGTH_VALIDATOR"

    const val SUBJECT_MIN_LENGTH_VALIDATOR: String = "SUBJECT_MIN_LENGTH_VALIDATOR"

    const val MESSAGE_MIN_LENGTH_VALIDATOR: String = "MESSAGE_MIN_LENGTH_VALIDATOR"

    const val FULL_NAME_MAX_LENGTH_VALIDATOR: String = "FULL_NAME_MAX_LENGTH_VALIDATOR"

    const val FULL_NAME_LENGTH_VALIDATOR: String = "FULL_NAME_LENGTH_VALIDATOR"

    const val EGYPT_COUNTRY_CODE = "EG"

}